server:
   port: 8503


spring:
   application:
      name: notification-service
   zipkin:
      base-url: http://localhost:9411/     
   rabbitmq:
      username: celal
      password: celal
   cloud:
      stream:
         bindings:
            input:
               destination: msqueue


eureka:
   client:
      serviceUrl:
         defaultZone: http://localhost:8500/eureka/